# Detecting blurred images
## Edge Detection
The images losses it's edges due to defocus and so the features are selected as edges through sobel and laplacian operators

## Sobel Edge Detection
Sobel Edge operator It is a edge detection operator based on gradient method i.e., the first order derivative method. Along x or along y or bi-directional. The edges are detected by convolving the kernel with actual image. The sobel operator kernel used here is bi-directional


## Robert Edge Operator
Roberts Edge Operator It is similar to Sobel operator gives the gradient magnitude highlighting the edges


## Laplacian Edge Operator
Laplacian Edge operator It is also an edge detection operator based on gradient methos but it calculated the second dervative od the data . It internally calls the sobel operator for first derivative.


## Zero-Crossing
Why Derivative? The edges can be deteced by finding the local maxima or minima of it's first derivative The edges can be deteced by finding the zero-crossing of it's second derivative

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
#print(os.listdir("../input"))
import matplotlib.pyplot as plt
import cv2
import sklearn
import seaborn as sb

from skimage.color import rgb2gray
from skimage.filters import laplace, sobel, roberts
# Any results you write to the current directory are saved as output.

In [3]:
print('Sobel operator:\n',np.matrix([[1,0,-1],[2,0,-2],[1,0,-1]]))
print('Laplacian operator:\n',np.matrix([[0,-1,0],[-1,4,-1],[0,-1,0]]))

Sobel operator:
 [[ 1  0 -1]
 [ 2  0 -2]
 [ 1  0 -1]]
Laplacian operator:
 [[ 0 -1  0]
 [-1  4 -1]
 [ 0 -1  0]]


In [14]:
def get_data(path,images):
    features=[]
    for img in images:
        print(img)
        feature=[]
        image_gray = cv2.imread(path+img,0)
        lap_feat = laplace(image_gray)
        sob_feat = sobel(image_gray)
        rob_feat = roberts(image_gray)
        feature.extend([img,lap_feat.mean(),lap_feat.var(),np.amax(lap_feat),
                        sob_feat.mean(),sob_feat.var(),np.max(sob_feat),
                        rob_feat.mean(),rob_feat.var(),np.max(rob_feat)])
        
        features.append(feature)
    return features

In [19]:
from glob import glob

path = "/Users/bab226/Pictures/test_dataset/"
#path = "/Users/bab226/Pictures/test_dataset/20190821_182219.jpg"
test_images = sorted(glob(path + "*.jpg"))
#test_images = [path]
#print(test_images)

test_features = get_data("", test_images)

/Users/bab226/Pictures/test_dataset/20190821_182219.jpg
/Users/bab226/Pictures/test_dataset/20191002_225540.jpg
/Users/bab226/Pictures/test_dataset/20191012_113442.jpg
/Users/bab226/Pictures/test_dataset/20191019_135455.jpg
/Users/bab226/Pictures/test_dataset/20191019_172548.jpg
/Users/bab226/Pictures/test_dataset/20191109_112448.jpg
/Users/bab226/Pictures/test_dataset/20200120_200955.jpg
/Users/bab226/Pictures/test_dataset/20200307_170020.jpg
/Users/bab226/Pictures/test_dataset/20200325_185453.jpg
/Users/bab226/Pictures/test_dataset/20200330_151519.jpg
/Users/bab226/Pictures/test_dataset/20200526_145239.jpg
/Users/bab226/Pictures/test_dataset/20200718_172114.jpg
/Users/bab226/Pictures/test_dataset/20200904_191741.jpg
/Users/bab226/Pictures/test_dataset/20200905_114459.jpg
/Users/bab226/Pictures/test_dataset/20211010_124904.jpg
/Users/bab226/Pictures/test_dataset/20211119_113427.jpg
/Users/bab226/Pictures/test_dataset/20211119_113429.jpg
/Users/bab226/Pictures/test_dataset/20211222_174

In [20]:
test_df = pd.DataFrame(test_features)
test_df.drop(0,axis=1,inplace=True)
test_df.head()

1         2         3         4         5         6         7  \
0  1.193196e-19  0.001765  0.827451  0.022101  0.001600  0.587477  0.019269   
1  8.522829e-20  0.003444  0.694118  0.030390  0.001270  0.608811  0.028787   
2  4.726653e-20  0.007488  1.086275  0.048585  0.003183  0.649731  0.041699   
3 -1.073884e-19  0.004625  1.250980  0.025794  0.002618  0.656530  0.023078   
4  6.319180e-20  0.000425  0.317647  0.016649  0.000294  0.268026  0.013784   

          8         9  
0  0.000992  0.595898  
1  0.000846  0.553386  
2  0.002454  0.630593  
3  0.002011  0.692226  
4  0.000174  0.231406

In [ ]:
test_df2 = pd.DataFrame(test_features)
test_df2['sharp'] = probabilities[:, 0]
test_df2['defocused'] = probabilities[:, 1]
test_df2['motion'] = probabilities[:, 2]
test_df2.head()

0             1         2  \
0  /Users/bab226/Pictures/test_dataset/20190821_1...  1.193196e-19  0.001765   
1  /Users/bab226/Pictures/test_dataset/20191002_2...  8.522829e-20  0.003444   
2  /Users/bab226/Pictures/test_dataset/20191012_1...  4.726653e-20  0.007488   
3  /Users/bab226/Pictures/test_dataset/20191019_1... -1.073884e-19  0.004625   
4  /Users/bab226/Pictures/test_dataset/20191019_1...  6.319180e-20  0.000425   

          3         4         5         6         7         8         9  \
0  0.827451  0.022101  0.001600  0.587477  0.019269  0.000992  0.595898   
1  0.694118  0.030390  0.001270  0.608811  0.028787  0.000846  0.553386   
2  1.086275  0.048585  0.003183  0.649731  0.041699  0.002454  0.630593   
3  1.250980  0.025794  0.002618  0.656530  0.023078  0.002011  0.692226   
4  0.317647  0.016649  0.000294  0.268026  0.013784  0.000174  0.231406   

      sharp  defocused    motion  
0  0.607874   0.002701  0.389425  
1  0.639446   0.008055  0.352499  
2  0.976228   0.000278  0.023495  
3  0.920407   0.000450  0.079143  
4  0.043012   0.720660  0.236328

In [48]:
# Sort by probability of sharpness:
pd.set_option('display.max_colwidth', None)
test_df2.sort_values(by='sharp', ascending=True, inplace=True)
print(test_df2)

                                                              0             1  \
52      /Users/bab226/Pictures/test_dataset/20250226_131818.jpg -1.388272e-19   
4       /Users/bab226/Pictures/test_dataset/20191019_172548.jpg  6.319180e-20   
9       /Users/bab226/Pictures/test_dataset/20200330_151519.jpg -2.257894e-18   
27      /Users/bab226/Pictures/test_dataset/20220417_223627.jpg  7.247497e-20   
54      /Users/bab226/Pictures/test_dataset/20250226_131823.jpg -1.115399e-19   
22      /Users/bab226/Pictures/test_dataset/20220410_220545.jpg -1.473816e-18   
5       /Users/bab226/Pictures/test_dataset/20191109_112448.jpg  4.776244e-19   
53      /Users/bab226/Pictures/test_dataset/20250226_131821.jpg -1.958666e-19   
10      /Users/bab226/Pictures/test_dataset/20200526_145239.jpg -7.126760e-19   
49      /Users/bab226/Pictures/test_dataset/20250226_131801.jpg  5.854307e-21   
17      /Users/bab226/Pictures/test_dataset/20211222_174153.jpg  2.668672e-19   
51      /Users/bab226/Pictur

In [23]:
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,f1_score, classification_report
import joblib

all_data = np.array(test_df)

# You can now use loaded_model to make predictions without retraining.
loaded_model = joblib.load('svm_model.joblib')
loaded_pred = loaded_model.predict(all_data)
#print("Loaded model Accuracy:",accuracy_score(y_valid,loaded_pred))

In [24]:
probabilities = loaded_model.predict_proba(all_data)

In [25]:
print(probabilities)

[[6.07873685e-01 2.70136909e-03 3.89424946e-01]
 [6.39445672e-01 8.05514350e-03 3.52499185e-01]
 [9.76227532e-01 2.77838741e-04 2.34946296e-02]
 [9.20406755e-01 4.50126308e-04 7.91431187e-02]
 [4.30122747e-02 7.20659587e-01 2.36328139e-01]
 [7.10984548e-02 3.97646335e-01 5.31255211e-01]
 [7.73853018e-01 3.88727942e-04 2.25758254e-01]
 [5.50150304e-01 3.62082989e-03 4.46228867e-01]
 [7.76708213e-01 3.36058252e-04 2.22955728e-01]
 [5.10229865e-02 5.48079699e-01 4.00897314e-01]
 [1.28178689e-01 1.01228064e-01 7.70593247e-01]
 [8.95882053e-01 1.00544171e-03 1.03112506e-01]
 [9.18111682e-01 5.36454992e-05 8.18346725e-02]
 [4.61542672e-01 1.44672409e-03 5.37010604e-01]
 [8.65083691e-01 3.66871115e-04 1.34549438e-01]
 [9.95206586e-01 1.39642305e-05 4.77944944e-03]
 [9.94972687e-01 1.50106713e-05 5.01230214e-03]
 [1.85781616e-01 4.44976357e-02 7.69720748e-01]
 [7.26460805e-01 4.30686266e-04 2.73108508e-01]
 [2.44631795e-01 3.48610279e-03 7.51882102e-01]
 [5.11726433e-01 5.03751467e-03 4.832360